In [19]:
import hanoi
import numpy as np

In [3]:
?hanoi.sim_generations

Signature:
hanoi.sim_generations(
    n_gen,
    mut_effect,
    genotype,
    mut_rate,
    mean_0,
    varcov_0,
    fit_func,
    n_gen_max=inf,
    seed=None,
    record=True,
    **kwargs,
)
Docstring:
Simulates multiple generations.

Arguments:
    n_gen :      Number of generations to simulate. 
                 n_gen = 0 runs simulation until mutations at all loci are fixed in the population.
    n_gen_max:   Maximum number of generations to simulate.
                 If n_gen > 0, n_gen_max is set to n_gen.
                 If n_gen == 0, simulation will stop if mutations do not fix before n_gen_max.
    mut_effect : hanoi.MutEffect representing the mutation effect.
    genotype :   2D np.ndarray of (L, N) representing the initial genotype table.
    mut_rate :   A float representing mutation rate per locus per generation.
    mean_0 :     2D np.ndarray of (n, N) representing expectation of n traits for a genotype of 0000...
    varcov_0 :   2D np.ndarray of (n, n) representin

In [28]:
d = hanoi.sample_data_1()

In [11]:
d.geno

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [14]:
d.mut_effect.show()

Number of traits n:
1
Number of trait pairs:
0
Number of loci L:
1
Mutation effect of mean:
[[1.]]
Mutation effect of variance:
[[1.]]
Mutation effect of covariance:
[]


In [20]:
d.mut_effect.var = (np.array([0]))

In [22]:
d.mut_effect.show()

Number of traits n:
1
Number of trait pairs:
0
Number of loci L:
1
Mutation effect of mean:
[[1.]]
Mutation effect of variance:
[0]
Mutation effect of covariance:
[]


In [23]:
d.z_ref

array([0.])

In [25]:
d.c_ref = np.array([[0]])

In [ ]:
d.

In [61]:
res = hanoi.sim_generations(n_gen = 0, mut_effect=d.mut_effect, fit_func="fit_gaus", genotype=d.geno, mean_0=d.z_ref, mut_rate=0, n_gen_max=1, record=False, varcov_0=d.c_ref, sigma = 0.001, z_opt = 0.5)

In [62]:
res[1].allele_freqs_next()

array([[0.]])