In [1]:
import hanoi
import numpy as np
import os

In [2]:
sample_data_1 = hanoi.sample_data_1()
M = sample_data_1.mut_effect
G = sample_data_1.geno
z_ref = sample_data_1.z_ref
c_ref = sample_data_1.c_ref

In [3]:
c_ref

array([[0.1]])

In [4]:
sim = hanoi.sim_generations(n_gen = 0, 
                            mut_effect = M,
                            genotype = G,
                            mut_rate = 0.0,
                            mean_0 = z_ref,
                            varcov_0 = c_ref,
                            fit_func = "fit_neutral"
                           )

In [5]:
sim = hanoi.sim_generations(n_gen = 10, 
                            mut_effect = M,
                            genotype = G,
                            mut_rate = 0.0,
                            mean_0 = z_ref,
                            varcov_0 = c_ref,
                            fit_func = "fit_neutral",
                            record=False
                           )

In [6]:
sim

[9, <hanoi.hanoi.Generation at 0x7e051d2795e0>]

In [18]:
%%time
sims = hanoi.run_replicates(n_reps = 10,
                            n_gen = 0,
                            mut_effect = M,
                            genotype = G,
                            mut_rate = 0.0,
                            mean_0 = z_ref,
                            varcov_0 = c_ref,
                            fit_func = "fit_neutral",
                            record = False
                           )

CPU times: user 10.1 ms, sys: 44.3 ms, total: 54.4 ms
Wall time: 146 ms


In [19]:
sims

[[226, <hanoi.hanoi.Generation at 0x7e051cc45c10>],
 [23, <hanoi.hanoi.Generation at 0x7e051cd7dcd0>],
 [66, <hanoi.hanoi.Generation at 0x7e051cc44290>],
 [308, <hanoi.hanoi.Generation at 0x7e051cc47050>],
 [243, <hanoi.hanoi.Generation at 0x7e051cc46cc0>],
 [1158, <hanoi.hanoi.Generation at 0x7e051cc45790>],
 [138, <hanoi.hanoi.Generation at 0x7e051cc45cd0>],
 [59, <hanoi.hanoi.Generation at 0x7e051cc45190>],
 [385, <hanoi.hanoi.Generation at 0x7e051cc45fd0>],
 [342, <hanoi.hanoi.Generation at 0x7e051cc456a0>]]

In [11]:
[sim[0] + 1 for sim in sims]

[10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

In [27]:
[gen.n_gen for gen in sims]

[150, 247, 240, 328, 213, 136, 356, 164, 231, 118]

In [23]:
[gen.n_gen for gen in sims]

[56, 259, 728, 55, 466, 485, 118, 90, 336, 51]

In [6]:
A = hanoi.comp_breed_val(mut_effect = M, genotype=G)

In [7]:
z = hanoi.sim_pheno(breed_val=A, mean_0=z_ref, varcov_0=c_ref)

In [8]:
w = hanoi.fit_gaus(sigma = 1, z=z, z_opt=[1])

In [9]:
w = hanoi.fit_multimodal(sigma = [1,1], p=[0.2, 0.8], z=z, z_opt=[0, 1])

In [10]:
w = hanoi.fit_step(z = z, boxes= np.array([[[0], [np.inf]]]))

In [11]:
w

array([1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.])

In [12]:
hanoi.sim_generation(mut_effect=M, genotype=G, fit_func = "fit_neutral", mean_0=z_ref, varcov_0=c_ref,mut_rate=0)

In [13]:
z = hanoi.sim_pheno(A, z_ref, c_ref)

In [14]:
hanoi.fit_neutral(z)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
hanoi.fit_gaus(sigma = 1, z = z, z_opt = [1])

array([0.97046783, 0.99100463, 0.54545813, 0.997698  , 0.77842417,
       0.65860987, 0.39401176, 0.79005127, 0.9916798 , 0.99591596,
       0.9599224 , 0.60184918, 0.56877575, 0.30434112, 0.91204938,
       0.73634658, 0.59596891, 0.92185419, 0.79724564, 0.71574619,
       0.80853695, 0.98921351, 0.9247822 , 0.94137382, 0.82800541,
       0.33953626, 0.99545399, 0.92977956, 0.7396389 , 0.74942996,
       0.66154975, 0.90538253, 0.45133239, 0.92804217, 0.79978466,
       0.99674482, 0.83116875, 0.88041303, 0.97147675, 0.99117276,
       0.91954735, 0.80724519, 0.96156233, 0.72135366, 0.18534367,
       0.69922688, 0.93499238, 0.47206829, 0.90402525, 0.96766851,
       0.68567042, 0.54063521, 0.59725901, 0.63348519, 0.65117509,
       0.72917116, 0.64739228, 0.6619462 , 0.63734761, 0.54544253,
       0.64834228, 0.53880079, 0.59648767, 0.54892692, 0.69521783,
       0.61039771, 0.55529043, 0.62104259, 0.58341837, 0.69173534,
       0.59976459, 0.62441276, 0.64712069, 0.64014946, 0.63106

In [16]:
w

array([1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1.])

In [17]:
A.show()

Number of traits:
 1
Number of trait pairs:
 0
Number of individuals:
 100
Breeding value of mean:
 [[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]
Breeding value of variance:
 [[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5
  0.5 0.5 0.5 0.5 0.5 0.5 0.5 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]
Breeding value of covariance:
 []
Breeding value of

In [18]:
sim.allele_freq_last()

array([0.])

In [19]:
sim.n_gen

174

In [20]:
sim = hanoi.sim_generations(n_gen = 0, 
                     mut_effect = M,
                      genotype = G,
                      mut_rate = 0.0,
                      mean_0 = z_ref,
                      varcov_0 = c_ref,
                      fit_func = "fit_neutral"
                     )
np.array([sim.n_gen, sim.allele_freq_last()[0]])

array([187.,   0.])

In [21]:
sample_data_1 = hanoi.sample_data_1()
M = sample_data_1.mut_effect
G = sample_data_1.geno
z_ref = sample_data_1.z_ref
c_ref = sample_data_1.c_ref

In [22]:
def sim_replicates(n_reps, mut_effect, genotype, mut_rate, mean_0, varcov_0, fit_func, **kwargs):
    out = np.full((n_reps, 2), np.nan)
    for i in range(n_reps):
        sim = hanoi.sim_generations(n_reps = n_reps, mut_effect = mut_effect, genotype = genotype, mut_rate = mut_rate, mean_0 = mean_0, varcov_0 = varcov_0, fit_func = fit_func, **kwargs)
        out[i] = sim.n_gen, sim.allele_freq_last()[0]
    return out

In [23]:
def sim_replicates_norec(n_reps, mut_effect, genotype, mut_rate, mean_0, varcov_0, fit_func, **kwargs):
    out = []
    for i in range(n_reps):
        sim = hanoi.sim_generations(n_reps = n_reps, mut_effect = mut_effect, genotype = genotype, mut_rate = mut_rate, mean_0 = mean_0, varcov_0 = varcov_0, fit_func = fit_func, **kwargs)
        out.append(sim)
    return out

In [24]:
hanoi.fit_step?

Signature: hanoi.fit_step(boxes, z)
Docstring:
z:     (N, n) array of n-dimensional phenotypes of N individuals.
boxes: (m, 2, n) array of m boxes, where boxes[i, 0, :] = lower bounds, boxes[i, 1, :] = upper bounds of i-th box. Fitness of phenotype within boxes is 1.
Returns: (N,) array of 0 or 1
File:      ~/SeaDrive/My Libraries/mylib/work/projects/python/packages/hanoi/hanoi/fitness.py
Type:      function

In [25]:
A = hanoi.comp_breed_val(mut_effect = M, genotype = G)

In [26]:
z = hanoi.sim_pheno(breed_val = A, mean_0 = z_ref, varcov_0 = c_ref)
hanoi.fit_step(boxes = np.array([[[0], [np.inf]]]), z=z)

array([1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0.])

In [27]:
z_ref

array([0.])

In [28]:
%%time
res = sim_replicates(n_reps = 100,
               n_gen = 1000, 
               mut_effect = M,
               genotype = G,
               mut_rate = 0.0,
               mean_0 = z_ref,
               varcov_0 = c_ref,
               fit_func = "fit_neutral"
              )

CPU times: user 5.27 s, sys: 0 ns, total: 5.27 s
Wall time: 5.27 s


In [29]:
%%time
res = sim_replicates_norec(n_reps = 100,
               n_gen = 1000, 
               mut_effect = M,
               genotype = G,
               mut_rate = 0.0,
               mean_0 = z_ref,
               varcov_0 = c_ref,
               fit_func = "fit_neutral", record = False
              )

CPU times: user 147 ms, sys: 0 ns, total: 147 ms
Wall time: 147 ms


In [30]:
res[0]

[999,
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0.]])]

# Cython

In [31]:
%load_ext cython

In [32]:
%%cython
import numpy as np
cimport numpy as np
import hanoi

def sim_replicates_c(int n_reps, object mut_effect, np.ndarray[np.float64_t, ndim = 2] genotype, double mut_rate, np.ndarray[np.float64_t, ndim = 1] mean_0, np.ndarray[np.float64_t, ndim = 2] varcov_0, str fit_func, **kwargs):
    cdef out = np.full((n_reps, 2), np.nan)
    cdef int i
    cdef object sim
    for i in range(n_reps):
        sim = hanoi.sim_generations(n_reps = n_reps, mut_effect = mut_effect, genotype = genotype, mut_rate = mut_rate, mean_0 = mean_0, varcov_0 = varcov_0, fit_func = fit_func, **kwargs)
        out[i] = sim.n_gen, sim.allele_freq_last()[0]
    return out


In [33]:
%%time
res = sim_replicates(n_reps = 100,
               n_gen = 0, 
               mut_effect = M,
               genotype = G,
               mut_rate = 0.0,
               mean_0 = z_ref,
               varcov_0 = c_ref,
               fit_func = "fit_neutral"
              )

CPU times: user 1.54 s, sys: 0 ns, total: 1.54 s
Wall time: 1.54 s


In [34]:
%%time
res = sim_replicates_c(n_reps = 100,
               n_gen = 0, 
               mut_effect = M,
               genotype = G,
               mut_rate = 0.0,
               mean_0 = z_ref,
               varcov_0 = c_ref,
               fit_func = "fit_neutral"
              )

CPU times: user 1.36 s, sys: 0 ns, total: 1.36 s
Wall time: 1.37 s


# Parallelise

In [ ]:
import concurrent.futures as futures
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor, as_completed
import numpy as np

In [37]:
import os
os.cpu_count()

14

In [38]:
[None] * 10

[None, None, None, None, None, None, None, None, None, None]

In [39]:
def run_replicates(n_reps, max_workers = os.cpu_count(), **kwargs):
    results = [None] * n_reps

    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        # Schedule all tasks
        futures = [executor.submit(hanoi.sim_generations, **kwargs) for _ in range(n_reps)]
        
        # Collect results as they finish
        for i, fut in enumerate(as_completed(futures)):
            results[i] = fut.result()
    return results

In [74]:
%%time
res = run_replicates(n_reps=10,
                     n_gen = 0, 
                     mut_effect = M,
                     genotype = G,
                     mut_rate = 0.0,
                     mean_0 = z_ref,
                     varcov_0 = c_ref,
                     fit_func = "fit_neutral",
                     max_workers=10,
                     record = True
                    )

CPU times: user 2.11 ms, sys: 87.5 ms, total: 89.6 ms
Wall time: 112 ms


In [75]:
res

In [73]:
np.array([res_i.allele_freq_last() for res_i in res])

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [78]:
%%time
res = run_replicates(n_reps=10,
                     n_gen = 0, 
                     mut_effect = M,
                     genotype = G,
                     mut_rate = 0.0,
                     mean_0 = z_ref,
                     varcov_0 = c_ref,
                     fit_func = "fit_neutral",
                     max_workers=10,
                     record = False
                    )

CPU times: user 3.9 ms, sys: 80 ms, total: 83.9 ms
Wall time: 101 ms


In [79]:
res

[[61,
  array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])],
 [61,
  array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])],
 [61,
  array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 

In [69]:
np.mean(np.array([i[1] for i in res]),axis = 2)/2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [82]:
sim = hanoi.sim_generations(n_gen = 0, fit_func="fit_neutral", genotype=G, mean_0=z_ref, mut_effect=M, mut_rate=0.0, record=True, varcov_0=c_ref)

In [88]:
sim.n_offspring.sum(axis = 1)

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 20

In [104]:
hanoi.cov_mtx((1,1), (1))

array([[1, 1],
       [1, 1]])

In [211]:
%%time
res = sim_replicates(1000,  
                     n_gen = 0, 
                     mut_effect = M,
                     genotype = G,
                     mut_rate = 0.0,
                     mean_0 = z_ref,
                     varcov_0 = c_ref,
                     fit_func = "fit_neutral")

CPU times: user 15.2 s, sys: 0 ns, total: 15.2 s
Wall time: 15.2 s


In [ ]:
def sim_replicates(n_reps, **kwargs):
    out = np.full((n_reps, 2), np.nan)
    for i in range(n_reps):
        sim = hanoi.sim_generations(**kwargs)
        out[i] = sim.n_gen, sim.allele_freq_last()[0]
    return out

In [40]:
np.array([[[1], [np.inf]]])[0, 1, :]

array([inf])

In [33]:
np.array([[[1], [np.inf]]]).shape

(1, 2, 1)