# Preparation for two-locus one-trait (1)

In [1]:
import numpy as np
from scipy.stats import norm, gaussian_kde
from matplotlib import pyplot as plt
from itertools import product
import hanoi
import pandas as pd

In [2]:
L = 2
n = 1
N = 100

In [3]:
M0 = np.column_stack([np.array([0, 0.9, 1, 1.1, 2]), np.zeros(5)]).reshape(5,n,L)
M1 = np.column_stack([np.array([0, 0.9, 1, 1.1, 2]), np.zeros(5)]).reshape(5,n,L)

In [4]:
M0

array([[[0. , 0. ]],

       [[0.9, 0. ]],

       [[1. , 0. ]],

       [[1.1, 0. ]],

       [[2. , 0. ]]])

In [5]:
M1

array([[[0. , 0. ]],

       [[0.9, 0. ]],

       [[1. , 0. ]],

       [[1.1, 0. ]],

       [[2. , 0. ]]])

In [6]:
V0 = np.column_stack([np.zeros(16),10 ** np.linspace(-2, 1, 16)]).reshape(16,n,L)
V1 = np.column_stack([np.zeros(16),10 ** np.linspace(-2, 1, 16)]).reshape(16,n,L)

In [7]:
V0

array([[[ 0.        ,  0.01      ]],

       [[ 0.        ,  0.01584893]],

       [[ 0.        ,  0.02511886]],

       [[ 0.        ,  0.03981072]],

       [[ 0.        ,  0.06309573]],

       [[ 0.        ,  0.1       ]],

       [[ 0.        ,  0.15848932]],

       [[ 0.        ,  0.25118864]],

       [[ 0.        ,  0.39810717]],

       [[ 0.        ,  0.63095734]],

       [[ 0.        ,  1.        ]],

       [[ 0.        ,  1.58489319]],

       [[ 0.        ,  2.51188643]],

       [[ 0.        ,  3.98107171]],

       [[ 0.        ,  6.30957344]],

       [[ 0.        , 10.        ]]])

In [8]:
V1

array([[[ 0.        ,  0.01      ]],

       [[ 0.        ,  0.01584893]],

       [[ 0.        ,  0.02511886]],

       [[ 0.        ,  0.03981072]],

       [[ 0.        ,  0.06309573]],

       [[ 0.        ,  0.1       ]],

       [[ 0.        ,  0.15848932]],

       [[ 0.        ,  0.25118864]],

       [[ 0.        ,  0.39810717]],

       [[ 0.        ,  0.63095734]],

       [[ 0.        ,  1.        ]],

       [[ 0.        ,  1.58489319]],

       [[ 0.        ,  2.51188643]],

       [[ 0.        ,  3.98107171]],

       [[ 0.        ,  6.30957344]],

       [[ 0.        , 10.        ]]])

In [9]:
parcombs = np.array(list(product(M0, M1, V0, V1)))

In [10]:
parcombs[0]

array([[[0.  , 0.  ]],

       [[0.  , 0.  ]],

       [[0.  , 0.01]],

       [[0.  , 0.01]]])

In [11]:
G = np.repeat([0,1,2], [25, 50, 25]).astype(float).reshape((1,100))

In [12]:
m0, m1, v0, v1 = parcombs[1234]

In [13]:
M_m = m1 - m0

In [14]:
M_m

array([[2., 0.]])

In [15]:
M_v = v1 - v0

In [16]:
M_v

array([[ 0.        , -3.95595284]])

In [17]:
m0.sum(axis = 1)

array([0.])

In [18]:
v0.sum(axis = 1)

array([3.98107171])

In [19]:
M_m

array([[2., 0.]])

In [20]:
z_ref = m0.sum(axis = 1)

In [21]:
z_ref

array([0.])

In [22]:
c_ref = v0.sum(axis = 1).reshape(1,1)

In [23]:
c_ref

array([[3.98107171]])

In [24]:
np.concatenate((M_m, M_v), axis = 0)

array([[ 2.        ,  0.        ],
       [ 0.        , -3.95595284]])

In [25]:
z_ref

array([0.])

In [26]:
c_ref

array([[3.98107171]])

In [27]:
G = np.repeat([0,1,2], [25, 50, 25]).astype(float).reshape((1,100)).repeat(2, axis = 0)

In [28]:
G

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2., 2.]])

In [40]:
M_m

array([[0., 0.]])

In [45]:
c_ref

array([[0.01]])

In [46]:
z_ref

array([0.])

In [43]:
M = hanoi.MutEffect(mean = np.array([[0,0]]), var = np.array([[0,0]]), cov=np.array([[]]))

In [44]:
M.show()

Number of traits n:
1
Number of trait pairs:
0
Number of loci L:
2
Mutation effect of mean:
[[0 0]]
Mutation effect of variance:
[[0 0]]
Mutation effect of covariance:
[]


In [68]:
M = hanoi.MutEffect(mean = M_m, var = M_v, cov=np.array([[]]))
res = hanoi.run_replicates(n_reps = 10, 
                           max_workers = 1,
                           n_gen = 0, 
                           genotype = G, 
                           mut_effect = M, 
                           record = False, 
                           mut_rate = 0.0, 
                           mean_0 = np.array([1.0]),
                           varcov_0 = np.array([[1.0]]), 
                           fit_func = "fit_step",
                           boxes = np.array([[[1], [np.inf]]])
                         )

In [69]:
res[0][1].allele_freqs_next().flatten()

array([1., 1.])

In [73]:
out = []
for i, (m0, m1, v0, v1) in enumerate(parcombs):
    if i < 2:
        print(f"{i} {i/len(parcombs):.2f} {m0} {m1} {v0} {v1}")
        M_m = m1 - m0
        M_v = v1 - v0
        z_ref = m0.sum(axis = 1)
        c_ref = v0.sum(axis = 1).reshape(1,1)
        M = hanoi.MutEffect(mean = M_m, var = M_v, cov=np.array([[]]))
        res = hanoi.run_replicates(n_reps = 3, 
                                   max_workers = 5,
                                   n_gen = 0, 
                                   genotype = G, 
                                   mut_effect = M, 
                                   record = False, 
                                   mut_rate = 0.0, 
                                   mean_0 = z_ref,
                                   varcov_0 = c_ref, 
                                   fit_func = "fit_step",
                                   boxes = np.array([[[1], [np.inf]]])
                             )
        #out.append([[m0, m1, v0, v1, res[j][0], res[j][1].allele_freqs_next()[0,0]] for j in range(len(res))])
        out.append([[m0[0,0], m1[0,0], v0[0,1], v1[0,1], res[j][0], res[j][1].allele_freqs_next()[0,0], res[j][1].allele_freqs_next()[0,1]] for j in range(len(res))])
out = np.array(out).reshape(-1, np.array(out).shape[2])
out_df = pd.DataFrame(out, columns = ["m0", "m1", "v0", "v1", "n_gen", "allele_fixed_locus_0", "allele_fixed_locus_1"])
out_df = out_df.astype({"n_gen": "int64", "allele_fixed_locus_0": np.float64, "allele_fixed_locus_1": np.float64})




0 0.00 [[0. 0.]] [[0. 0.]] [[0.   0.01]] [[0.   0.01]]
1 0.00 [[0. 0.]] [[0. 0.]] [[0.   0.01]] [[0.         0.01584893]]


In [76]:
out_df

,m0,m1,v0,v1,n_gen,allele_fixed_locus_0,allele_fixed_locus_1
0,0.0,0.0,0.01,0.010000,1,NaN,NaN
1,0.0,0.0,0.01,0.010000,1,NaN,NaN
2,0.0,0.0,0.01,0.010000,1,NaN,NaN
3,0.0,0.0,0.01,0.015849,1,NaN,NaN
4,0.0,0.0,0.01,0.015849,1,NaN,NaN
5,0.0,0.0,0.01,0.015849,1,NaN,NaN


IndexError: list index out of range

In [206]:
np.array([m0, m1]).flatten()

AttributeError: 'numpy.ndarray' object has no attribute 'as_list'

In [195]:
out

[[[array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 0.01]),
   1,
   np.float64(nan)],
  [array([0., 0.]),
   array([0., 0.]),
   array([0.  , 0.01]),
   array([0.  , 